language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key:
    secure: KuNgxPAlcY5qquD3HpjbefEyvSrKLdov2kNfp9d5CIyxaYgoPW1h3bdD3tU8U71mOd9L2j7/pc/ihyVC5dxb0D/ISgLWT842gXOkwyDbaQDVSid1IVCw71AZyEIz1LRi0qCV8p6xaC8Y+kyqjWT/lrqjYKgS+Ut5jtH2OwFju5E=
  on:
    tags: true
    repo: simbo/collection.stylus
before_script:
- npm install -g gulp
