language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key: ${NPM_API_KEY}
  on:
    tags: true
    repo: simbo/collection.stylus
before_script:
- npm install -g gulp
env:
  global:
    secure: Ddyxoq3G/bUik1V0KfMyP9sQLxTM4ouI1QfXcMwfCdMo4F5U2iVtNX3Q4UBXN/RlKMa0OrYKa6zwn3TvmZdLJOGSDZVTw+hp5AMmwnwISDKY64MuEGSHfWPs1vK9hqKZs61/vSpJUozI1xSnUh2+dSirvpfvrmlzxA1lnTww494=
